name: OpenWeather App CI
on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  buil:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unit tests
        run: ./gradlew test
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.1
        with: 
          name: openweatherapp
          path: app/build/outputs/apk/debug/app-debug.apk 
